### ISSUE TITLE
Missing previews in Journal, and UnicodeWarning in log

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-datastore#16]
```log
/usr/lib/python2.7/dist-packages/sugar3/datastore/datastore.py:113: \
UnicodeWarning: Unicode unequal comparison failed to convert both \
arguments to Unicode - interpreting them as being unequal
  if key not in self._properties or self._properties[key] != value:
```

**Comment by quozl** [comment]
May be the cause of missing previews in Journal.

**Comment by mdengler** [comment]
That 6f4fcae ("Port to Python 3") commit is bad in that respect.  The metadata was stored as bytes before, and there is a big comment about how it has to be stored as bytes and how, coincidentally, `str(bytes_data)` didn't interfere, but *would in the future*.  The future has come, and the current port/code is blindly converting everything to `unicode`.  It should not be.

**Comment by quozl** [comment]
Thanks.  I agree.  I'll look at it in about four hours if nobody else does.

**Comment by pro-panda** [comment]
The C extension code (`metadatareader.c`) would not accept `bytes` as an argument; From memory, it would either raise a segmentation fault, or convert `b'<string>'` to `"b'<string>'"`

**Comment by mdengler** [comment]
> From memory, All values are converted to `bytes` in
> [metadatareader.add_property]
> and ultimately returning strings of format `"b'<string>'"`

Seems like there should be no `string`s (or `StringIO`) in the python code, then, and rather `bytes` (or `BytesIO`).

**Comment by martin-langhoff** [comment]
I agree with @mdengler 's comments. Py2 string handling was /mostly/ 8-bit clean, and Py3 string handling is most definitely not. IMHO datastore should not ever try to interpret them -- I'd remove all casts to string. 

Unfortunately I don't have a test env handy to run Sugar components (and I'm about to have to  dodge a hurricane). I do have some recent/current Fedora systems.

**Comment by quozl** [comment]
Think I've fixed it.  

https://github.com/sugarlabs/sugar-datastore/pull/18
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/428
