### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-datastore#7]
Port to Python 3 and the Sugar Toolkit for GTK+ 3.

Requires https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/382 to be completed for at least `sugar3.datastore`, `sugar3.mime`, `sugar3.env`, and `sugar3.logger`.

Progress goals:

- [x] port C and Python code in `src/carquinyol`,
- [x] port make files, and test "make install",
- [x] test running the datastore,
- [x] verify that existing datastores are binary compatible,
- [x] ~regenerate documentation,~ add documentation,
- [x] <s>make local Fedora and Debian packages for testing by others.</s>

_this is an issue for tracking a major project which is larger than one person's contributions, so developers should make pull requests to satisfy any of these items, and not ask to own the issue._

**Comment by Aniket21mathur** [comment]
> * verify that existing datastores are binary compatible,
> *

@pro-panda @quozl How to de test this?

**Comment by quozl** [comment]
I'd rather not constrain your creativity on that.  I did have a long explanation, which I deleted.  But the requirement can be phrased another way; what will happen when a user of Sugar with a precious Journal of years of work suffers the indignity of an automated or organisationally forced upgrade to 0.116?  Users are children and teachers.

**Comment by Aniket21mathur** [comment]
>  But the requirement can be phrased another way; what will happen when a user of Sugar with a precious Journal of years of work suffers the indignity of an automated or organisationally forced upgrade to 0.116?

Thanks, I think I got it. We need to somehow save the `datastore` entries and check  whether we can use it on different versions or systems without building it again?

As `datastore` is formed insided `.sugar` each time sugar is installed on the system, how do we ensure that the new `datastore` dir is not formed? 

Should I try manually replacing the _new_ empty one with the _old_ one, and check whether it is working?

**Comment by pro-panda** [comment]
> Should I try manually replacing the new empty one with the old one, and check whether it is working?
Don't ask about making an attempt, just do it ;-) (especially when doing takes the same time as asking)

**Comment by pro-panda** [comment]
> As datastore is formed insided .sugar each time sugar is installed on the system, how do we ensure that the new datastore dir is not formed?

If dir already exists, don't overwrite it. Keep it simple

**Comment by Aniket21mathur** [comment]
Thanks @pro-panda. I followed the following steps:-
* Installed sugar for a new user.
* Populated the journal.
* Kept the `datastore` directory in `.sugar` safe.
* Deleted the `.sugar` directory.
* Installed sugar again, restarted the system, the journal is now empty as expected.
* Used the old `datastore` in the new `.sugar` directory and started the system again.
* The journal is populated with the old entries as expected.

From the above tests it seems like datastore is binary compatible, though I don't know whether it is the correct way to test or not.

**Comment by quozl** [comment]
> Thanks, I think I got it. We need to somehow save the `datastore` entries and check whether we can use it on different versions or systems without building it again?

Sure, if you like.  Write a test plan.  Look at `cp -ra` or `rsync -ra` for ways to copy the datastore.  The D-Bus server `datastore-service` should not be running when you do this, otherwise the copy you make may be incomplete.

> As `datastore` is formed insided `.sugar` each time sugar is installed on the system, how do we ensure that the new `datastore` dir is not formed?

No, that's not correct.  The datastore is created automatically if it does not exist.  This happens when Sugar is _started_, not when Sugar is _installed_, and not when Sugar is _upgraded_.

> Should I try manually replacing the _new_ empty one with the _old_ one, and check whether it is working?

Again, remember that the D-Bus server `datastore-service` should not be running when you change the files in which the datastore is kept.  Therefore Sugar should not be running.

**Comment by Aniket21mathur** [comment]
> Therefore Sugar should not be running.

Thanks. I ensured it while doing the above tests, please see my comment above. :-)

**Comment by quozl** [comment]
And were the two `datastore-service` instances running different Python versions?

**Comment by Aniket21mathur** [comment]
> And were the two `datastore-service` instances running different Python versions?

No, tested with Python 3 versions only, I will test for cross versions, thanks for pointing out.

**Comment by Aniket21mathur** [comment]
Tested across different versions as well, used `datastore` created with Python 2 version with Python 3, following the same steps as above works fine!

Thanks!

**Comment by quozl** [comment]
Good, thanks.  Hiding these replies as outdated.

**Comment by Aniket21mathur** [comment]
Packages for testing.
https://github.com/Aniket21mathur/sugar-datastore-python3
@quozl @pro-panda please review.
Thanks!

**Comment by quozl** [comment]
https://github.com/Aniket21mathur/sugar-datastore-python3/issues/1
